### PR TITLE
color-schemes: change titlebar and window background color

### PR DESCRIPTION
**Pull request by guoyunhe**
Before:

image

After:

image

### CODE REVIEW

**Comment by Vogtinator** [comment]
I'm against this - if the colors were close to breeze there'd be no point in having an openSUSE scheme at all.

In fact, I just noticed now that the default openSUSE look-and-feel does not use the openSUSE color scheme by default, should we change that?

**Comment by guoyunhe** [comment]
The color is still from openSUSE branding guidelines https://opensuse.github.io/branding-guidelines/

The green titlebar doesn't look good. So I changed it to openSUSE Primary Color 2.

For window background color, the openSUSE branding guidelines doesn't defined any light grey colors. So I just used the same as Breeze.

**Comment by guoyunhe** [comment]
I changed openSUSE look and feel to use openSUSE color scheme in this PR.

**Comment by Vogtinator** [comment]
@hellcp: What do you think?

**Comment by hellcp** [comment]
I like that change, I feel like the blue strip under the titlebar from breeze would make it better, if that's possible. The lighter grey of the background certainly look nicer. I do think there is nothing wrong with being close to breeze, the colour scheme looks unique enough to differentiate the two, between the bluer titlebar and greener selections.

**Comment by guoyunhe** [comment]
Closing because the change will be included in #12 ;-)

**Pull request closed without merging**
